PYTHON=python
UV=uv
TOML=pyproject.toml

.PHONY: install test venv init run run-module

install:
	$(UV) pip install -r $(TOML)

test:
	pytest -q 

venv:
	$(UV) venv .

init: 
	$(UV) venv .
	$(UV) pip install -r $(TOML)

run:
	$(UV) sync
	$(UV) run {{ terminal_command }}

run-module:
	$(UV) run python -m src.python_cli.modules.$(MODULE)
