PYTHON=python
ENV_FILE=environment.yml

.PHONY: env-create env-update test run init

env-create:
	conda env create -f $(ENV_FILE)

env-update:
	conda env update -f $(ENV_FILE) --prune

init:
	eval "$(conda shell.bash hook)" 
	conda activate {{ project_name }}
	$(PYTHON) -m pip install .

test:
	pytest -q 

run:
	eval "$(conda shell.bash hook)" 
	conda activate {{ project_name }}
	$(PYTHON) -m {{ project_name }}

run-module:
	eval "$(conda shell.bash hook)" 
	conda activate {{ project_name }}
	run python -m src.python_cli.modules.$(MODULE)
